app = "typingmind-mcp-server"
primary_region = "fra"

[http_service]
auto_start_machines = true
auto_stop_machines = false    # <-- keep machines running 24/7
force_https = true
internal_port = 8080          # <-- matches MCP default port
min_machines_running = 1      # <-- ensure at least 1 machine is always running
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 1024
